# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f13bd3bba27f670f42c7f27147a27befb78232f6e4e3ca6adacbe0ace61bc811522f23c4d83a3073d73e5b80844422127135e3b62708cae6deec6847c29e3f5c

test:
  secret_key_base: e13786bc296b58ef9a297dd26d9f27d6d9c090d56ecb6f3d31a515601645b187780455bde90f87111c8c621782b4dbfa9b376a05a979c264300d86f1ec46e0c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
